import { db, intakeItemsTable, type IntakeItemRow } from "@workspace/db";
import { logger } from "./logger";

const SEED_INTAKE = [
  {
    source: "zoho_cliq" as const,
    sourceChannel: "#systems-ops",
    senderName: "Priya Nair",
    senderHandle: "@priya",
    senderRole: "Systems Lead",
    receivedAt: "2026-07-02 09:14",
    rawMessage: "Can we add a new automation in Zoho Flow to sync qualifier form fields into CRM? The QualifierConnect workflow keeps missing the source field.",
    cleanedSummary: "Request to add a Zoho Flow automation syncing qualifier form fields into CRM; QualifierConnect misses the source field.",
    detectedType: "crm_or_zoho_request" as const,
    suggestedDestination: "automation-registry" as const,
    sensitivity: "normal" as const,
    reviewOwner: "Carmen" as const,
    status: "needs_review" as const,
    duplicateRisk: "likely" as const,
    relatedProjectNames: ["QualifierConnect", "Automation Registry"],
    reviewerNotes: "",
    finalActionTaken: null,
    nextStep: "Carmen reviews systems, Zoho, and automation requests.",
    classificationReason: "Mentions Zoho / CRM / Cliq / workflow language, which is Carmen's systems territory.",
    auditLog: [{ id: "al-1a", timestamp: "2026-07-02 09:14", actor: "System", action: "Captured from Zoho Cliq (test mode) and classified as CRM/Zoho request." }],
  },
  {
    source: "whatsapp" as const,
    sourceChannel: "Founders chat",
    senderName: "Rose Taylor",
    senderHandle: "+1 (555) 010-2211",
    senderRole: "Founder & CEO",
    receivedAt: "2026-07-02 08:41",
    rawMessage: "Rose and Carmen need to align on the new pricing proposal before the client call Friday. Let's mind meld on this - I have concerns about the tier structure.",
    cleanedSummary: "Rose wants a private Rose/Carmen alignment session on the new pricing proposal ahead of Friday's client call.",
    detectedType: "rose_carmen_mind_meld" as const,
    suggestedDestination: "mind-meld" as const,
    sensitivity: "private_leadership" as const,
    reviewOwner: "Rose and Carmen" as const,
    status: "new" as const,
    duplicateRisk: "none" as const,
    relatedProjectNames: [] as string[],
    reviewerNotes: "",
    finalActionTaken: null,
    nextStep: "Review privately in the Mind Meld Room before any broader routing.",
    classificationReason: "Mentions founder-alignment language (Rose and Carmen, mind meld), so it belongs in the private Mind Meld space.",
    auditLog: [{ id: "al-2a", timestamp: "2026-07-02 08:41", actor: "System", action: "Captured from WhatsApp (test mode) and flagged private leadership." }],
  },
  {
    source: "zoho_cliq" as const,
    sourceChannel: "#general",
    senderName: "Jordan Lee",
    senderHandle: "@jordan",
    senderRole: "Marketing Lead",
    receivedAt: "2026-07-01 16:22",
    rawMessage: "Idea: what if we built a client-facing status page that pulls from the Command Center? Clients keep asking where their onboarding stands.",
    cleanedSummary: "Idea for a client-facing status page powered by Command Center data to answer onboarding-status questions.",
    detectedType: "idea" as const,
    suggestedDestination: "idea-backlog" as const,
    sensitivity: "normal" as const,
    reviewOwner: "Unassigned" as const,
    status: "needs_review" as const,
    duplicateRisk: "possible" as const,
    relatedProjectNames: ["Command Center Build"],
    reviewerNotes: "",
    finalActionTaken: null,
    nextStep: "Add to the idea backlog as a draft and check for duplicates.",
    classificationReason: "Uses idea language (what if, client-facing status page), so it is captured as a draft idea.",
    auditLog: [{ id: "al-3a", timestamp: "2026-07-01 16:22", actor: "System", action: "Captured from Zoho Cliq (test mode) and classified as idea." }],
  },
  {
    source: "whatsapp" as const,
    sourceChannel: "Ops chat",
    senderName: "Dee Okafor",
    senderHandle: "+1 (555) 010-4477",
    senderRole: "Compliance Lead",
    receivedAt: "2026-07-01 11:05",
    rawMessage: "Blocked on Document Collection again - the client invoice dispute means legal wants us to pause outreach. Need a decision on how to proceed.",
    cleanedSummary: "Document Collection blocked; legal wants outreach paused amid a client invoice dispute. Decision needed on next steps.",
    detectedType: "blocker" as const,
    suggestedDestination: "command-center-task" as const,
    sensitivity: "legal_sensitive" as const,
    reviewOwner: "Rose and Carmen" as const,
    status: "needs_review" as const,
    duplicateRisk: "possible" as const,
    relatedProjectNames: ["Document Collection"],
    reviewerNotes: "",
    finalActionTaken: null,
    nextStep: "Sensitive blocker - joint review before any task is drafted.",
    classificationReason: "Uses blocked / waiting language and contains legal-sensitive content, so it needs careful joint review.",
    auditLog: [{ id: "al-4a", timestamp: "2026-07-01 11:05", actor: "System", action: "Captured from WhatsApp (test mode); legal-sensitive language detected." }],
  },
  {
    source: "manual" as const,
    sourceChannel: "Manual test entry",
    senderName: "Sam Rivera",
    senderHandle: "sam@collabos.test",
    senderRole: "Automation Engineer",
    receivedAt: "2026-06-30 14:50",
    rawMessage: "Process update: we changed how CAG automations get registered. New SOP - every automation needs a registry entry with owner and rollback plan before deploy.",
    cleanedSummary: "SOP change proposal: CAG automations now require a registry entry with owner and rollback plan before deploy.",
    detectedType: "process_update" as const,
    suggestedDestination: "company-brain-update" as const,
    sensitivity: "normal" as const,
    reviewOwner: "Rose and Carmen" as const,
    status: "routed" as const,
    duplicateRisk: "possible" as const,
    relatedProjectNames: ["Automation Registry"],
    reviewerNotes: "Good candidate for the SOP Library once approved.",
    finalActionTaken: "Company Brain update proposal drafted (pending approval).",
    nextStep: "Draft a Company Brain update proposal - never write directly to approved records.",
    classificationReason: "Describes an SOP / process change, so it becomes a proposed Company Brain update pending approval.",
    auditLog: [
      { id: "al-5a", timestamp: "2026-06-30 14:50", actor: "System", action: "Captured via manual test entry and classified as process update." },
      { id: "al-5b", timestamp: "2026-06-30 15:12", actor: "Carmen Vega", action: "Routed as Company Brain update proposal - awaiting Rose and Carmen approval." },
    ],
  },
  {
    source: "zoho_cliq" as const,
    sourceChannel: "#random",
    senderName: "Tomas Beck",
    senderHandle: "@tomas",
    senderRole: "Sales Lead",
    receivedAt: "2026-06-30 10:08",
    rawMessage: "lol nice one",
    cleanedSummary: "Casual reaction message with no actionable content.",
    detectedType: "ignore_or_noise" as const,
    suggestedDestination: "no-action" as const,
    sensitivity: "normal" as const,
    reviewOwner: "Unassigned" as const,
    status: "archived" as const,
    duplicateRisk: "none" as const,
    relatedProjectNames: [] as string[],
    reviewerNotes: "",
    finalActionTaken: "Archived as noise.",
    nextStep: "Likely noise - archive unless a reviewer disagrees.",
    classificationReason: "Very short message with no actionable keywords - likely chatter or noise.",
    auditLog: [
      { id: "al-6a", timestamp: "2026-06-30 10:08", actor: "System", action: "Captured from Zoho Cliq (test mode) and classified as noise." },
      { id: "al-6b", timestamp: "2026-06-30 10:31", actor: "Rose Taylor", action: "Archived - no action required." },
    ],
  },
];

export function serializeIntakeItem(row: IntakeItemRow) {
  return {
    id: row.id,
    source: row.source,
    sourceChannel: row.sourceChannel,
    senderName: row.senderName,
    senderHandle: row.senderHandle,
    senderRole: row.senderRole,
    receivedAt: row.receivedAt,
    rawMessage: row.rawMessage,
    cleanedSummary: row.cleanedSummary,
    detectedType: row.detectedType,
    suggestedDestination: row.suggestedDestination,
    sensitivity: row.sensitivity,
    reviewOwner: row.reviewOwner,
    status: row.status,
    duplicateRisk: row.duplicateRisk,
    relatedProjectNames: row.relatedProjectNames,
    reviewerNotes: row.reviewerNotes,
    finalActionTaken: row.finalActionTaken,
    nextStep: row.nextStep,
    classificationReason: row.classificationReason,
    auditLog: row.auditLog,
  };
}

export async function seedIntakeIfEmpty(): Promise<void> {
  const existing = await db.select({ id: intakeItemsTable.id }).from(intakeItemsTable).limit(1);
  if (existing.length > 0) return;
  await db.insert(intakeItemsTable).values(SEED_INTAKE);
  logger.info({ count: SEED_INTAKE.length }, "Seeded external intake items");
}
